# NVDA Configuration File
schemaVersion = 22

[general]
language = en_US
saveConfigurationOnExit = False
askToExit = False
playStartAndExitSounds = False
loggingLevel = INFO
showWelcomeDialogAtStartup = False

[development]
enableScratchpadDir = True

[keyboard]
keyboardLayout = desktop
NVDAModifierKeys = 7

[speech]
synth = oneCore
symbolLevel = 100
trustVoiceLanguage = True

[braille]
display = noBraille

[update]
autoCheck = False
startupNotification = False
allowUsageStats = False
askedAllowUsageStats = True

[addonStore]
automaticUpdates = disabled
